select chr(65) from DUAL;
select concat(ENAME, ' is a '), JOB from EMP; 
select initcap('the lion') from DUAL;
select lower('MY NAME IS KHS') from dual;
select lpad('khs', 13, '*#') from DUAL;
select rpad('khs', 13, '*#') from DUAL;
select ltrim('     LAST WORDxy', ' ') from DUAL;
select replace('JACK and JUE', 'J', 'BL') from DUAL;
select substr('ABCDEFG', 3, 2) from DUAL;
select ascii('A') from DUAL;
select greatest('CC', 'ABCDE', 'CA') from DUAL;
select least('CC', 'ABCDE', 'CA') from DUAL; 
select instr('CORPORATE FLOOR', 'OR', 3, 2) from DUAL;
select ENAME, nvl(COMM, 100) from EMP; 
select ENAME, nvl(COMM, 100) from EMP;
select abs(-10) from dual;
select ceil(11.012) from dual;
select ceil(-11.012) from dual;
select floor(-12.999) from dual;
select round(12.5) from dual;
select round(-12.5) from dual;
select cos(90) from dual;
select exp(2) from dual;
select log(10, 100) from dual;
select mod(11, 4) from dual;
select power(3, 3) from dual;
select trunc(15.789, 2) from DUAL;
select HIREDATE, add_months(HIREDATE, -7) from EMP;
select last_day('21/6/14') from dual;
select SYSDATE, NEXT_DAY(SYSDATE,4) from DUAL;
select SYSDATE, to_char(SYSDATE, 'D') from DUAL;
select SYSDATE, to_char(SYSDATE, 'DAY') from DUAL;
select SYSDATE, to_char(SYSDATE, 'DY') from DUAL; 
select SYSDATE, to_char(SYSDATE, 'DD') from DUAL;
select SYSDATE, to_char(SYSDATE, 'MM') from DUAL;
 select SYSDATE, to_char(SYSDATE, 'MON') from DUAL; 
 select SYSDATE, to_char(SYSDATE, 'MONTH') from DUAL; 
 select SYSDATE, to_char(SYSDATE, 'YY') from DUAL; 
 select SYSDATE, to_char(SYSDATE, 'YEAR') from DUAL; 
 select SYSDATE, to_char(SYSDATE, 'MM-DD-YY') from DUAL;
 select SYSDATE, to_char(SYSDATE, 'MI') from DUAL;
 select SYSDATE, to_char(SYSDATE, 'fmAM HH:MI:SS') from DUAL;
 select SYSDATE, to_char(SYSDATE, 'YYYY-MM-DD AM HH:MI:SS DAY') from dual;
 select ENAME, SAL from EMP where SAL=min(SAL);
 select stddev(COMM) from EMP;
 select variance(COMM) from EMP;
 select DEPTNO, round(avg(SAL)) from EMP group by DEPTNO;
 select DEPTNO, round(avg(SAL)) from EMP 
          where SAL>=2000 group by DEPTNO order by round(avg(SAL)) desc;
          select DEPTNO, JOB, count(EMPNO) from EMP
    group by DEPTNO, JOB
	  order by DEPTNO desc, JOB desc;