delete from hu_today;
delete from hu_find;
delete from hu_bbsRe;
delete from hu_bbs;
delete from hu_guestbookRe;
delete from hu_guestbook;
delete from hu_myitem;
delete from hu_friendment;
delete from hu_menu;
delete from hu_myhome;
delete from hu_friend;
delete from hu_group;
delete from hu_paper;
delete from hu_buy;
delete from hu_gift;
delete from hu_store;
delete from hu_login_user;
delete from hu_login;
delete from hu_member;

commit;
